version: '3.8'

# docker compose up -d

services:
  webapp:
    image: netcomwebuiapp:latest # image we want to build
    build: . # location of Dockerfile
    container_name: netcomwebapp
    ports:
      - 1234:8080