apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calvin-app-deploy
  name: calvin-internal-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: calvin-app-deploy
  type: LoadBalancer
status:
  loadBalancer: {}