# create a docker build pipeline
name: web docker build & push image to DockerHub pipeline

on:
    push:
        branches:
            - "main"
            - "dev"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pre-checks
              run: |
                uname -r
                whoami
                cat /etc/os-release
                docker version
                docker-compose version

                if [ "$GITHUB_REF" = "refs/heads/main" ]; then
                  echo "tag=latest" >> $GITHUB_ENV
                elif [ "$GITHUB_REF" = "refs/heads/dev" ]; then
                  echo "tag=dev" >> $GITHUB_ENV
                fi
            
            - name: Checkout repository
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6

            - name: Use docker compose to build
              run: |
                docker compose up -d
                docker compose ps
            
            - name: Health check of running web container
              run: |
                (curl -sSf localhost:1234/health.html > /dev/null && echo "SUCCESS: STATUS 200") || (echo "FAILURE: STATUS 404" && exit 1)
            
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #v3.1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
              with:
                images: ${{ secrets.DOCKERHUB_IMAGE_REPO_FQRN }}
            
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 #v5.3.0
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_IMAGE_REPO_FQRN }}:${{ env.tag }}
                labels: ${{ steps.meta.outputs.labels }}
        
            - name: docker clean up
              run: |
                docker compose down
                docker logout
