# create a docker build pipeline
name: web docker build pipeline

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pre-checks
              run: |
                uname -r
                whoami
                cat /etc/os-release
                docker version
                docker-compose version
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use docker compose to build
              run: |
                docker compose up -d
                docker compose ps
            - name: Health check of running web container
              run: |
                curl -sSf localhost:1234/health.html && echo "SUCCESS: STATUS 200"
            - name: docker clean up
              run: |
                docker compose down