# create a docker build pipeline
name: web docker build pipeline

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pre-checks
              run: |
                uname -r
                whoami
                cat /etc/os-release
                docker version
                docker-compose version
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use docker compose to build
              run: |
                docker compose up -d
                docker compose ps
            
            - name: Health check of running web container
              run: |
                (curl -sSf localhost:1234/health.html > /dev/null && echo "SUCCESS: STATUS 200") || (echo "FAILURE: STATUS 404")
            
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Docker Hub push
              run: |
                docker push docker.io/calvinlideveloper/netcomwebuiapp:latest
        
            - name: docker clean up
              run: |
                docker compose down
                docker logout