# create a docker build pipeline
name: web multi job pipeline

on:
    push:
        branches:
            - "dev1"

jobs:
    sast:
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
          
          - name: SonarQube Scan
            run: |
              sonar-scanner.bat -D"sonar.projectKey=calvinli-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"

    build:
        runs-on: ubuntu-latest
        needs: sast
        steps:
            - name: just checking general message
              run: |
                echo "Python version"
                python -V