# create a docker build pipeline
name: web multi job pipeline

on:
    push:
        branches:
            - "dev1"

jobs:
    sast:
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
          
          - name: SonarQube Scan
            run: |
              sonar-scanner.bat -D"sonar.projectKey=calvinli-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"
          
          - name: Upload Artifact
            uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
            with:
              name: sonarqube_artifact
              path: |
                Dockerfile
                compose.yaml
                html/
                !**/.git*
                !**/*.md
              retention-days: 5

    build:
        runs-on: ubuntu-latest
        needs: sast
        steps:
          - name: Download sonarqube artifact from sast
            uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e #v4.1.7
            with:
              name: sonarqube_artifact

          - name: Use docker compose to build
            run: |
              docker compose up -d
              docker compose ps
          
          - name: Health check of running web container
            run: |
              (curl -sSf --retry 3 --retry-all-errors localhost:1234/health.html > /dev/null && echo "SUCCESS: STATUS 200") || (echo "FAILURE: STATUS 404" && exit 1)